// src/app/modules/work/components/forcely/forcely.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'work/forcely',
  templateUrl: './forcely.component.html',
  styleUrls: ['./forcely.component.css']
})
export class ForcelyComponent implements OnInit {
  constructor() {}
  ngOnInit() {}
}

<div class="row">
  <div class="col text-center">
    <h2>Forcely</h2>
  </div>
</div>
<div class="row">
  <p><a href="https://itunes.apple.com/US/app/id1420946432?mt=8" target="_blank">Forcely</a>
    provides code enforcement officers with a quick and easy way to log their day to day activities.</p>
  <p>This is a company that I started in order to reduce the amount of inefficiencies in
    local government. I conducted research, as well as designed and built, the entire
    <a href="https://itunes.apple.com/US/app/id1420946432?mt=8" target="_blank">app</a> myself using Google’s
    <a href="https://firebase.google.com/docs/firestore/" target="_blank">Firestore</a> as the back-end.
    Currently I have one <a href="https://goo.gl/Pv5rj7" target="_blank"> city</a> using the app.</p>
  <p>I’m also currently working on an <a href="https://angular.io/" target="blank">angular</a> web dashboard
    for Forcely to accompany the iOS app. This will allow city supervisors to gain insights into the activities
    their code enforcement officers are logging.</p>
  <p><a href="mailto:tony@burrus.me">Send me an email</a> if you’d like to hear more about why I started this
    company and how it’s solving problems in local government or if you’d like a test account to try out the app.</p>
</div>
<div class="row">
  <div class="col text-center images">
    <a href="assets/img/forcely-1.jpg"><img class="ios" src="assets/img/forcely-1.jpg" alt="forcely 1"></a>
    <a href="assets/img/forcely-2.jpg"><img class="ios" src="assets/img/forcely-2.jpg" alt="forcely 2"></a>
    <a href="assets/img/forcely-3.jpg"><img class="ios" src="assets/img/forcely-3.jpg" alt="forcely 3"></a>
    <a href="assets/img/forcely-4.jpg"><img class="ios" src="assets/img/forcely-4.jpg" alt="forcely 4"></a>
  </div>
</div>
<!-- TODO: row/col with forcely dashboard image -->
<div class="row justify-content-center" id="last">
  <p class="keywords"><i>Angular, Bootstrap, CSS, Firebase, Firestore, Google Places, HTML, MVC, RxJS, Swift, Typescript</i></p>
</div>

// src/views/Forcely.vue
<template>
    <div class="work">
        <Header :showBackButton=true />
        <div class="content">
            <p>
                <span class="work-title">Forcely</span> 
                provided code enforcement officers with a quick and easy way to log their day to day activities.
            </p>
            <p>
                This is a company I started in 2018 to reduce the amount of inefficiencies in 
                local government. I conducted research, designed, and built the entire 
                <a href="https://itunes.apple.com/US/app/id1420946432?mt=8" target="_blank">app</a> 
                myself using Google’s 
                <a href="https://firebase.google.com/docs/firestore/" target="_blank">Firestore</a> 
                as the back-end. I also built a web dashboard in 
                <a href="https://angular.io/" target="blank">angular</a> 
                to accompany the iOS app. This allowed city supervisors to gain 
                insights into the activities their code enforcement officers were logging.
            </p>
            <p>
                I've since closed this business, but I did have one 
                <a href="https://goo.gl/Pv5rj7" target="_blank"> city</a> 
                using the platform for a while.
            </p>
            <div class="images" v-viewer="{transition: false}">
                <img src="@/assets/img/forcely-1.jpg" alt="App onboarding flow 1/4">
                <img src="@/assets/img/forcely-2.jpg" alt="App onboarding flow 2/4">
                <img src="@/assets/img/forcely-3.jpg" alt="App onboarding flow 3/4">
                <img src="@/assets/img/forcely-4.jpg" alt="App onboarding flow 4/4">
            </div>
        </div>
        <Footer />
    </div>
</template>

<script>
import Footer from "@/components/Footer.vue"
import Header from "@/components/Header.vue"

import "viewerjs/dist/viewer.css"
import VueViewer from "v-viewer"
import Vue from "vue"
Vue.use(VueViewer)

export default {
    name: "Forcely",
    components: {
        Footer,
        Header,
    },
}
</script>

<style scoped>
</style>
