// src/app/modules/work/components/hotwire/hotwire.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'work/hotwire',
  templateUrl: './hotwire.component.html',
  styleUrls: ['./hotwire.component.css']
})
export class HotwireComponent implements OnInit {
  constructor() {}
  ngOnInit() {}
}

<div class="row">
  <div class="col text-center">
    <img id="hotwireLogo" src="assets/img/hotwire-logo.png" alt="hotwire logo">
  </div>
</div>
<div class="row">
  <p><a href="https://www.hotwire.com/" target="_blank">Hotwire</a> helps you get great deals on
    name-brand hotels and car rentals around the world at a fraction of the price.</p>
</div>
<div class="row">
  <div class="col text-center">
    <h4 class="section-title">iOS</h4>
  </div>
  <p>As an <a href="https://itunes.apple.com/us/app/hotwire/id566635048?mt=8" target="_blank">iOS</a>
    developer here I worked on implementing in-app customer service messaging as well as updating the
    reviews section on the details screen to name a few. I learned a lot about how an agile engineering
    team operates and picked up a lot of new skills along the way.</p>
</div>
<div class="row desktop">
  <div class="col-6 text-center">
    <h5 class="subsection-title">Messaging</h5>
    <div class="row images">
      <div class="col-6">
        <a href="assets/img/hw-liveperson-1.png"><img class="ios" src="assets/img/hw-liveperson-1.png" alt="hotwire ios messaging 1"></a>
      </div>
      <div class="col-6">
      <a href="assets/img/hw-liveperson-2.png"><img class="ios" src="assets/img/hw-liveperson-2.png" alt="hotwire ios messaging 2"></a>
      </div>
    </div>
  </div>
  <div class="col-6 text-center">
    <h5 class="subsection-title">Reviews</h5>
    <div class="row images">
      <div class="col-6">
        <a href="assets/img/hw-reviews-1.png"><img class="ios" src="assets/img/hw-reviews-1.png" alt="hotwire ios reviews 1"></a>
      </div>
      <div class="col-6">
        <a href="assets/img/hw-reviews-2.png"><img class="ios" src="assets/img/hw-reviews-2.png" alt="hotwire ios reviews 2"></a>
      </div>
    </div>
  </div>
</div>
<div class="row mobile">
  <div class="col text-center">
    <h5 class="subsection-title">Messaging</h5>
    <img class="ios" src="assets/img/hw-liveperson-1.png" alt="hotwire ios messaging 1">
    <img class="ios" src="assets/img/hw-liveperson-2.png" alt="hotwire ios messaging 2">
    <h5 class="subsection-title">Reviews</h5>
    <img class="ios" src="assets/img/hw-reviews-1.png" alt="hotwire ios reviews 1">
    <img class="ios" src="assets/img/hw-reviews-2.png" alt="hotwire ios reviews 2">
  </div>
</div>
<div class="row justify-content-center">
  <p class="keywords"><i>MVVM, Objective-C, RxSwift, Swift, VIPER</i></p>
</div>
<div class="row">
  <div class="col text-center">
    <h4 class="section-title" id="angularSection">Angular</h4>
  </div>
  <p>While working on the UX Labs team, I often found it frustrating to recruit users for moderated
    studies. To solve this problem, I built an angular web app that tapped into to our customer
    database to automate the entire recruiting process. This project was a learning experience for
    me as it was the first time I built a web app from scratch. I was responsible for all the research,
    design, and front-end development on this project.</p>
</div>
<div class="row justify-content-center">
  <div class="col text-center">
    <a href="assets/img/hw-automation-1.png"><img class="web" src="assets/img/hw-automation-1.png" alt="hotwire angular image 1"></a>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col">
    <a href="assets/img/hw-automation-2.png"><img class="web" src="assets/img/hw-automation-2.png" alt="hotwire angular image 2"></a>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col">
    <a href="assets/img/hw-automation-3.png"><img class="web" src="assets/img/hw-automation-3.png" alt="hotwire angular image 3"></a>
  </div>
</div>
<div class="row justify-content-center">
  <p class="keywords"><i>Angular, AWS, Bootstrap, CSS, HTML, Typescript</i></p>
</div>
<div class="row" id="last">
  <p><a href="mailto:tony@burrus.me">Send me an email</a> if you’d like to hear more about
    the type of work I’ve been doing at Hotwire.</p>
</div>

// src/views/Hotwire.vue
<template>
    <div class="work">
        <Header :showBackButton=true />
        <div class="content">
            <p>
                <span class="work-title">Hotwire</span> 
                helps you get great deals on name-brand hotels and car rentals around the world 
                at a fraction of the price.
            </p>
            <p>
                As an 
                <a href="https://itunes.apple.com/us/app/hotwire/id566635048?mt=8" target="_blank">iOS</a> 
                developer here I worked on implementing in-app customer service messaging as well as updating 
                the reviews section on the details screen to name a few. I learned a lot about how an agile 
                engineering team operates and picked up a lot of new skills along the way.
            </p>
            <p>
                I also spent some time working on the UX Labs team and I often found it frustrating to recruit 
                users for moderated studies. To solve this problem, I built an angular web app that tapped into 
                our customer database to automate the entire recruiting process. This project was a learning experience 
                for me as it was the first time I built a web app from scratch. I was responsible for all the research,
                design, and front-end development on this project.
            </p>
            <div class="images" v-viewer="{transition: false}">
                <img src="@/assets/img/hw-liveperson-1.png" alt="In-app messaging (LivePerson) for customer service">
                <img src="@/assets/img/hw-liveperson-2.png" alt="In-app messaging (LivePerson) for customer service">
                <img src="@/assets/img/hw-reviews-1.png" alt="hotwire-reviews-1">
                <img src="@/assets/img/hw-reviews-2.png" alt="hotwire-reviews-2">
                <img src="@/assets/img/hw-automation-1.png" alt="hotwire-automation-1">
                <img src="@/assets/img/hw-automation-2.png" alt="hotwire-automation-2">
                <img src="@/assets/img/hw-automation-3.png" alt="hotwire-automation-3">
            </div>
        </div>
        <Footer />
    </div>
</template>

<script>
import Footer from "@/components/Footer.vue"
import Header from "@/components/Header.vue"

import "viewerjs/dist/viewer.css"
import VueViewer from "v-viewer"
import Vue from "vue"
Vue.use(VueViewer)

export default {
    name: "Hotwire",
    components: {
        Footer,
        Header,
    },
}
</script>

<style scoped>
</style>
