// src/app/modules/work/components/stormy/stormy.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'work/stormy',
  templateUrl: './stormy.component.html',
  styleUrls: ['./stormy.component.css']
})
export class StormyComponent implements OnInit {
  constructor() {}
  ngOnInit() {}
}

<div class="row">
  <div class="col text-center">
    <h2>Stormy</h2>
  </div>
</div>
<div class="row">
  <p><a href="https://github.com/burrus/stormy" target="_blank">Stormy</a>
    was a single-page weather app that allowed you to quickly grab the weather forecast
    from anywhere in the world. I used the <a href="https://darksky.net/dev" target="_blank">
    Dark Sky Weather API</a> to grab weather conditions. The app is no longer available on
    the App Store but the code is open source and freely available on Github.</p>
</div>
<div class="row" id="email">
  <p><a href="mailto:tony@burrus.me">Send me an email</a> if you’d like to hear more
    about how I built Stormy.</p>
</div>
<div class="row">
  <div class="col text-center images">
    <a href="assets/img/stormy-1.png"><img class="ios" src="assets/img/stormy-1.png" alt="stormy 1"></a>
    <a href="assets/img/stormy-2.png"><img class="ios" src="assets/img/stormy-2.png" alt="stormy 2"></a>
  </div>
</div>
<div class="row justify-content-center" id="last">
  <p class="keywords"><i>Dark Sky Weather, Google Places, MVVM, Swift</i></p>
</div>

// src/views/Stormy.vue
<template>
    <div class="work">
        <Header :showBackButton=true />
        <div class="content">
            <p>
                <span class="work-title">Stormy</span> 
                was a single-page weather app that allowed you to quickly grab the 
                weather forecast from anywhere in the world. I used the 
                <a href="https://darksky.net/dev" target="_blank">Dark Sky Weather API</a> 
                to grab weather conditions. This app was based on an app from 
                <a href="https://teamtreehouse.com/burrus" target="_blank">Treehouse</a>, 
                but I expanded upon it by adding several other features.
            </p>
            <div class="images" v-viewer="{transition: false}">
                <img src="@/assets/img/stormy-1.png" alt="Home screen with weather forecast">
                <img src="@/assets/img/stormy-2.png" alt="City search">
            </div>
        </div>
        <Footer />
    </div>
</template>

<script>
import Footer from "@/components/Footer.vue"
import Header from "@/components/Header.vue"

import "viewerjs/dist/viewer.css"
import VueViewer from "v-viewer"
import Vue from "vue"
Vue.use(VueViewer)

export default {
    name: "Stormy",
    components: {
        Footer,
        Header,
    },
}
</script>

<style scoped>
</style>
